# from src.image_processing import clean_extracted_text_img
from src.text_processing import clean_extracted_text_pdf
from src.text_processing import clean_extracted_text_txt
from src.extract_values import extract_medical_data_from_full_blood_test